### ISSUE TITLE
No 'cd' command present

### ISSUE THREAD

**Issue by joalricha869** [joalricha869/PyPrompt#4]
### This command may not be implemented into any version of PyPrompt

- Reason: ```cd``` function requires the implementation of ```main(current_dir)``` which crashes the terminal

**Comment by joalricha869** [comment]
THIS WILL NEVER BE IMPLEMENTED! Reason why i added cmd, bash, zsh commands

**Comment by IdkDwij** [comment]
@joalricha869 maybe you should make a QUESTIONS SECTION IN THE README INSTEAD OF OPENING ISSUES

**Comment by joalricha869** [comment]
i forgor about this

**Comment by joalricha869** [comment]
> THIS WILL NEVER BE IMPLEMENTED! Reason why i added cmd, bash, zsh commands

screw you lazy dev

**Comment by joalricha869** [comment]
> THIS WILL NEVER BE IMPLEMENTED! Reason why i added cmd, bash, zsh commands

ah yes TOTALLY NOT IMPLEMENTED

me an idiot dev

**Comment by IdkDwij** [comment]
why havent you still added cd or tried to do it by yourself

**Comment by IdkDwij** [comment]
dont try to use mine as a example its very not understandable

**Comment by joalricha869** [comment]
It works tho @IdkDwij

**Comment by IdkDwij** [comment]
But it's made by me and Nathan, not you, so it's not your code then, you should make a cd by yourself that works with pyprompt made for pyprompt.

**Comment by joalricha869** [comment]
pyprompt is literally an expansion to Termithon

**Comment by IdkDwij** [comment]
Then make it so that pyprompt doesn't use my code and instead can be implemented into termithon with a function

**Comment by IdkDwij** [comment]
And I also told you to NOT USE MY CD COMMAND

**Comment by joalricha869** [comment]
b r u v

either way it was going to be broken anyways LMAO

**Comment by IdkDwij** [comment]
That isnt a excuse, just code it yourself, its not that hard to create a cd command with a different way

**Comment by joalricha869** [comment]
whatever man also termithon is dead so no one really cares at this point about termithon

**Comment by joalricha869** [comment]
im trying to expand my audience  (besides me lmao)

**Comment by IdkDwij** [comment]
btw im working on something called jaminal
