### ISSUE TITLE
No build for macOS

### ISSUE THREAD

**Issue by IdkDwij** [joalricha869/PyPrompt#6]
im on my mac since its like 10 i am extremely lazy so im not turning on my laptop make mac build now

**Comment by IdkDwij** [comment]
also there is error on mac

**Comment by joalricha869** [comment]
dwij just stop spamming

**Comment by joalricha869** [comment]
and also remember my hackintosh is bricked af so I cant now DWIJ

**Comment by IdkDwij** [comment]
:(

**Comment by joalricha869** [comment]
imagine

**Comment by IdkDwij** [comment]
thanks for adding to label to screw me @joalricha869  -💯 social credit

**Comment by joalricha869** [comment]
my mac is bricked so i cant also why u still here (I should question the same too... rip)

**Comment by joalricha869** [comment]
> im on my mac since its like 10 i am extremely lazy so im not turning on my laptop make mac build now

lazy dev perfectly describes u dwij

**Comment by joalricha869** [comment]
for being a lazy dev -1 trillion social credit

**Comment by IdkDwij** [comment]
thankssss ❤️

**Comment by joalricha869** [comment]
if u continue working on termithon +10000 trillion social credit

**Comment by IdkDwij** [comment]
f u

**Comment by joalricha869** [comment]
damn stop being a lazy dev update termithon now

**Comment by joalricha869** [comment]
MAC BUILD WHEN I GET A MAC

**Comment by IdkDwij** [comment]
Lmao imagine not having mac couldn't be me + you had to send a apology to rohan lmao

**Comment by joalricha869** [comment]
i spoke to rohans brother, hes in period 6 with me nowwww

**Comment by joalricha869** [comment]
dum dum

**Comment by IdkDwij** [comment]
IK who Rohan's brother u monkey

**Comment by joalricha869** [comment]
thas not ok, u cant call me monkey

**Comment by joalricha869** [comment]
im not reporting u btw

**Comment by IdkDwij** [comment]
We evolved from monkeys lmao

**Comment by joalricha869** [comment]
ok i guess
