### ISSUE TITLE
PYPROMPT 1.6.1 BETA 3 DELAYED (Closed)

### ISSUE THREAD

**Issue by IdkDwij** [joalricha869/PyPrompt#7]

**Comment by joalricha869** [comment]
bruh school exists DWIJ

**Comment by joalricha869** [comment]
also u cant be talking u haven’t updated termithon in 6 months

**Comment by IdkDwij** [comment]
> bruh school exists DWIJ

I barely have time to do anything so don't talk

**Comment by joalricha869** [comment]
also i updated to python 3.11 and stuff is broken so update is delayed @IdkDwij

**Comment by joalricha869** [comment]
jus saying

**Comment by IdkDwij** [comment]
you done have to change title
